root: true
env:
  browser: true
  node: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
parser: '@babel/eslint-parser'
parserOptions:
  sourceType: module
  requireConfigFile: false
  allowImportExportEverywhere: false
  ecmaFeatures:
    globalReturn: false
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    plugins:  
      - '@typescript-eslint'
    extends:
      - plugin:@typescript-eslint/recommended
    parser: '@typescript-eslint/parser'
