root: true
env:
  browser: true
  node: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
parser: '@babel/eslint-parser'
parserOptions:
  sourceType: module
  allowImportExportEverywhere: false
  ecmaFeatures:
    globalReturn: false
rules:
  no-debugger: 0
  no-unused-vars: 1
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    plugins:
      - '@typescript-eslint'
    extends:
      - plugin:@typescript-eslint/recommended
    parser: '@typescript-eslint/parser'
globals:
  task: readonly
  describe: readonly
  before: readonly
  it: readonly
  __ENVIRONMENT__: readonly
  __BLOCKCHAIN_NAME__: readonly
  __GOOGLE_ANALYTICS_ENABLED__: readonly
  __GOOGLE_ANALYTICS_ID__: readonly
  __SENTRY_ENABLED__: readonly
  __SENTRY_DSN__: readonly
